# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: pwd
    - run: npm ci
    - run: npm test
      env:
        HOST: localhost
        DBUSER: root
        PASSWORD: pass
        DATABASE: voyage
        JWT_SECRET: secret
        SALT_ROUNDS: 8
        CLOUDINARY_NAME: name
        CLOUDINARY_API_KEY: apikey
        CLOUDINARY_API_SECRET: sec
        CI: true
